#server:
#  port: 8010
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/app_test_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: root
##  application:
##    name: user-service
##  redis:
##    host: localhost
##    port: 6379
##    jedis:
##      pool:
##        max-wait: 30000
##        max-active: 100
##        max-idle: 20
##        min-idle: 0
##    timeout: 3000
##    database: 1
##mybatis-plus:
##  mapper-locations: classpath:mapper/sms/*.xml
##  global-config:
##    db-config:
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/app_test_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: root
server:
  port: 8010