#server:
#  port: 8080
#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/order/**
#          filters:
#            - StripPrefix=1
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/user/**
#          filters:
#            - StripPrefix=1
#        - id: product-route
#          uri: lb://product-service
#          predicates:
#            - Path=/product/**
#          filters:
#            - StripPrefix=1
#        - id: auth-route
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**
#          filters:
#            - StripPrefix=1
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#  application:
#    name: gateway-service